# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"


platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task:"test")
  end

private_lane :upload_to_slack do |options|
	file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
	file_name = file_path.gsub(/\/.*\//,"")
	sh "echo Uploading " + file_name + " to Slack"
	sh "curl https://slack.com/api/files.upload -F token=\"xoxp-731733228049-739977885431-737653107540-7b7c3bbe9d3b83dc41d17b2ae650f325\" 
-F 
channels=\"#network\" -F title=\"" + file_name + "\" - F filename=\"" + file_name +"\" -F
file=@" + file_path
end

lane :slackbuild do
	gradle(task: "assembleRelease")
	slack(message: "Build Successful")
	upload_to_slack()
end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
